***************
*** 7,13 ****
  # ccflags-y := -DDEBUG
  # asflags-y := -DDEBUG
  
- KBUILD_AFLAGS	:=$(KBUILD_AFLAGS:-msoft-float=-Wa,-mfpu=softvfp+vfp)
  LDFLAGS		+=--no-warn-mismatch
  
  obj-y			+= vfp.o
--- 7,13 ----
  # ccflags-y := -DDEBUG
  # asflags-y := -DDEBUG
  
+ KBUILD_AFLAGS	:=$(KBUILD_AFLAGS:-msoft-float=-Wa,-mfpu=softvfp+vfp -mfloat-abi=soft)
  LDFLAGS		+=--no-warn-mismatch
  
  obj-y			+= vfp.o
