***************
*** 23,29 ****
  obj-$(CONFIG_OC_ETM)		+= etm.o
  
  obj-$(CONFIG_ISA_DMA_API)	+= dma.o
- obj-$(CONFIG_ARCH_ACORN)	+= ecard.o 
  obj-$(CONFIG_FIQ)		+= fiq.o fiqasm.o
  obj-$(CONFIG_MODULES)		+= armksyms.o module.o
  obj-$(CONFIG_ARTHUR)		+= arthur.o
--- 23,29 ----
  obj-$(CONFIG_OC_ETM)		+= etm.o
  
  obj-$(CONFIG_ISA_DMA_API)	+= dma.o
+ obj-$(CONFIG_ARCH_ACORN)	+= ecard.o
  obj-$(CONFIG_FIQ)		+= fiq.o fiqasm.o
  obj-$(CONFIG_MODULES)		+= armksyms.o module.o
  obj-$(CONFIG_ARTHUR)		+= arthur.o
***************
*** 69,73 ****
  head-y			:= head$(MMUEXT).o
  obj-$(CONFIG_DEBUG_LL)	+= debug.o
  obj-$(CONFIG_EARLY_PRINTK)	+= early_printk.o
  
  extra-y := $(head-y) init_task.o vmlinux.lds
--- 69,75 ----
  head-y			:= head$(MMUEXT).o
  obj-$(CONFIG_DEBUG_LL)	+= debug.o
  obj-$(CONFIG_EARLY_PRINTK)	+= early_printk.o
+ obj-$(CONFIG_IPIPE)	+= ipipe.o
+ obj-$(CONFIG_IPIPE_ARM_KUSER_TSC) += ipipe_tsc.o ipipe_tsc_asm.o
  
  extra-y := $(head-y) init_task.o vmlinux.lds
